### ISSUE TITLE
Missing required input "source-path"

### ISSUE THREAD

**Issue by nikolailehbrink** [SamKirkland/web-deploy#13]
**Bug Description**
When I open my workflow file than there is linting error, displaying, that there is a missing required input, although the `source-path` shouldn't be required

**My Action Config**
```yaml
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #   push:
  #     branches: ["main"]
  #   pull_request:
  #     branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 SSH-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 💻 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔨 Build Project
        run: npm run production

      - name: 📂 Sync files
        # https://github.com/SamKirkland/web-deploy
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_SERVER }}
          remote-user: ${{ secrets.SSH_USERNAME }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: 22
          destination-path: ./www/public_html/
          rsync-options: >
            --dry-run
            --archive
            --verbose
            --compress
            --delete-after
            --human-readable
            --exclude-from=.github/workflows/deploy/rsync-exclude.txt

```
Here is a screenshot:
![image](https://user-images.githubusercontent.com/38915700/231262861-27dc4631-e7c6-4b1b-91f6-f705ddec6fc6.png)
