### ISSUE TITLE
Error: The process '/usr/bin/rsync' failed with exit code 255

### ISSUE THREAD

**Issue by mimoudix** [SamKirkland/web-deploy#16]
**Bug Description**

**My Action Config**
```yaml
on:
  push:
    # !!!!!!! TODO Fill Out !!!!!!!
```

**My Action Log**
```
   # Paste Log here
```

**Comment by michellavezzo** [comment]
> **Bug Description** A clear and concise description of what the bug is.
> 
> **My Action Config**
> 
> ```yaml
> on:
>   push:
>     # !!!!!!! TODO Fill Out !!!!!!!
> ```
> 
> **My Action Log**
> 
> ```
>    # Paste Log here
> ```

You need to set the folder user ownership at your server.

- Make sure the destination directory is owned by the user running rsync.
- Use chown to change ownership if needed. For example: 
`sudo chown -R user /path/to/destination`

"user" is your server username

**Comment by michellavezzo** [comment]
Also if you do not have the rsync installed in your linux server, you need to run 

`sudo apt update && sudo apt install rsync -y`

**Comment by mimoudix** [comment]
Hey @michellavezzo I managed to get it working after installing Rsync—thank you so much! 

Regarding ownership permissions, I encountered a similar issue while using LAMP Packaged by Bitnami on a Lightsail VPS. I couldn't create files until I stumbled upon this fix:

```
sudo chown -R bitnami:daemon /opt/bitnami/apache/htdocs
sudo chmod -R g+w /opt/bitnami/apache/htdocs
```
Do you think this setup should work fine?

I've got another question about the rsync options. It appears that the deployment doesn't work when specifying exclusions without these options: --archive --verbose --compress --human-readable --progress --delete-after. Are these necessary? If so, any idea why?

Thanks in advance for your help! 🙏

**Comment by michellavezzo** [comment]
> Hey @michellavezzo I managed to get it working after installing Rsync—thank you so much!
> 
> Regarding ownership permissions, I encountered a similar issue while using LAMP Packaged by Bitnami on a Lightsail VPS. I couldn't create files until I stumbled upon this fix:
> 
> ```
> sudo chown -R bitnami:daemon /opt/bitnami/apache/htdocs
> sudo chmod -R g+w /opt/bitnami/apache/htdocs
> ```
> 
> Do you think this setup should work fine?
> 
> I've got another question about the rsync options. It appears that the deployment doesn't work when specifying exclusions without these options: --archive --verbose --compress --human-readable --progress --delete-after. Are these necessary? If so, any idea why?
> 
> Thanks in advance for your help! 🙏

To be honest, I don't know how to answer your questions hehe, but I hope a good citizen has his answers.

**Comment by Aatmik-Sanghvi** [comment]
Can any one check the below image and help me on it. I am setting CI/CD for AWS ec2. Trying to solve the error for more than 2 days but am not getting the proper solution on the internet 😥. 
Thank you in advance.
![deploy error](https://github.com/user-attachments/assets/35dcca3d-830f-479e-86d2-2e3536f02ca1)

**Comment by mimoudix** [comment]
@Aatmik-Sanghvi  can you share me your workflow code ?

**Comment by mimoudix** [comment]
@Aatmik-Sanghvi try this one and don't forget to give ur TARGET PATH permissions 
```
"on": push
name: Publish Website
jobs:
  web-deploy:
    name: "\U0001F680 Deploy Website Every Commit"
    runs-on: ubuntu-latest
    steps:
      - name: "\U0001F69A Get Latest Code"
        uses: actions/checkout@v3
      - name: "\U0001F4C2 Sync Files"
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: "${{ secrets.DEPLOY_HOST }}"
          remote-user: "${{ secrets.DEPLOY_USER }}"
          private-ssh-key: "${{ secrets.DEPLOY_PRIVATE_KEY }}"
          destination-path: ~/htdocs
          rsync-options:
            --archive --verbose --compress --human-readable --progress --delete-after
            --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md
            --exclude=webpack.config.js
            --exclude=.gitignore --exclude=config.php --exclude=secrets.php --exclude=node_modules/ --exclude=.vscode/
            --exclude=package.json --exclude=package-lock.json --exclude=purgecss.config.js --exclude=tailwind.config.js
            --exclude=input.css --exclude=composer.json --exclude=composer.lock --exclude=content/uploads/ --exclude=install.php --exclude=App/Ajax/install.php --exclude=webpack.config.js --exclude=App/logs/ --exclude=update_bd.sql
```
