### ISSUE TITLE
Node.js 16 deprecation warning

### ISSUE THREAD

**Issue by wiegertschouten** [SamKirkland/web-deploy#25]
**Bug Description**
I'm getting a warning on every run, saying the following:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, SamKirkland/web-deploy@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**My Action Config**
```yaml
on: 
  push:
    branches:
      - staging
name: 🏗️ Deploy staging
jobs:
  web-deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 🧶 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: 📦 Install Dependencies
      run: npm install

    - name: 🏗️ Build assets
      run: npm run build

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ vars.DEPLOY_HOST }}
        remote-user: ${{ vars.DEPLOY_USER }}
        destination-path: ${{ vars.DEPLOY_PATH_STAGING }}
        private-ssh-key: ${{ secrets.DEPLOY_KEY }}
        rsync-options: --archive --verbose --compress --human-readable --progress --delete-after --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore --exclude=node_modules --exclude=.parcel-cache/
```
The FTP Deploy action was recently updated to Node 20, is this also possible for Web Deploy?
