### ISSUE TITLE
dist folder not syncing

### ISSUE THREAD

**Issue by bilalmalkoc** [SamKirkland/web-deploy#26]
I added `.git-ftp-include` file and placed `!dist/` code but still not pushing dist folder to server.

Here is my config:

```
name: 🚀 Deploy website on push

on:
  push:
    branches:
      - live

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 21
    - run: npm install
    - run: npm run build

    - name: Checkout again
      uses: actions/checkout@v4

    - name: 📂 Push files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.FTP_SERVER }}
        remote-user: ${{ secrets.SSH_USERNAME }}
        private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        destination-path: /home/server/htdocs/x.com/wp-content/plugins/x/
        rsync-options: --archive --verbose --compress --human-readable --progress --delete-after --exclude=src* --exclude=node_modules* --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore	

```
