### ISSUE TITLE
configuration example

### ISSUE THREAD

**Issue by reactmore** [SamKirkland/web-deploy#7]
**My Action Config**
```yaml
on:
  push:
  - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.server}}
        remote-user: ${{ secrets.user}}
        private-ssh-key: ${{ secrets.SSH_KEY }}
        ssh-port: ${{ secrets.port}}
        destination-path: ~/core/
        rsync-options: --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore --exclude=public/uploads/*
```

It works when uploading to the server but rsync removes the folders  vendor and .env how can these 2 things not be deleted on the server?
